/** api 公共出口：功能服务层（一个功能一个文件），框架层只从这里 import。 */
export { cloneRepo, getRepoById, initRepo, listRecentRepos, openRepo } from './repo';
export { getRepoStatus } from './status';
export { watchRepoStatus } from './events';
export { getRepoConfig, setRepoConfig } from './config';
export { abortOperation, assertNoOperationInProgress, continueOperation, getOperation } from './operation';
export { getLogPage, streamLogEvents } from './log';
export { getFileDiff, getFileVersions, streamDiffEvents } from './diff';
export { getFileBlame } from './blame';
export { getFileHistory } from './history';
export { getCommittedPage } from './committed';
export { searchCommitsService } from './search';
export { applyHunkStaging, applyStaging } from './staging';
export { createCommit } from './commit';
export { applyBranchAction, getBranches } from './branch';
export { applyCheckout } from './checkout';
export { applyReset, undoCommit } from './reset';
export { continueMergeOperation, mergeBranchIntoCurrent } from './merge';
export { getConflictContents, getConflicts, resolveConflict } from './conflict';
export { applyStashAction, getStashes } from './stash';
export { getSettings, updateSettings } from './settings';
export { applyChangelistAction, getChangelists } from './changelist';
export { applyPatchService, createPatch, deletePatch, getPatches } from './patch';
export { applyShelfAction, getShelves } from './shelf';
export { getConsole } from './console';
export { addIgnore, getIgnore, getIgnoreTemplates, putIgnore } from './ignore';
export { deleteAccount, listAccounts, upsertAccount } from './auth';
export { applyRemoteAction, fetchRepo, getRemotes, pullRepo, pushRepo } from './remote';
export { getRebaseTodo, rebaseBranch, runInteractiveRebaseService } from './rebase';
export { cherryPick, revert } from './pick';
export { applyTagAction, getTags } from './tag';
export { updateProject } from './update';
export { toServiceError } from './errors';
